### ISSUE TITLE
Configuration options for an environment

### ISSUE THREAD

**Issue by ThomasRubini** [ThomasRubini/cloud-paas#21]

**Comment by rodriguezdamien** [comment]
Config ? Dans la CLI ?

**Comment by ThomasRubini** [comment]
Something that would allow you to configure the kubernetes deployment, to set environment variables.

I'm probably imagining a `paas-cli env edit` command that would open a yaml file using your EDITOR, with a format like this:
```
env:
  APP_USER: admin
  APP_PASSWORD: admin
  WHATEVER_YOU_WANT: 1
```
which would then be applied to the kubernetes deployment
